INSERT INTO decks (title, description, visibility, source_format)
VALUES
    ('Java: fundamentos modernos', 'Conceitos centrais de Java moderno para APIs e aplicacoes backend.', 'PUBLIC', 'MANUAL'),
    ('Python: fundamentos para ciencia de dados', 'Sintaxe, estruturas e praticas de Python aplicadas a analise e automacao.', 'PUBLIC', 'MANUAL'),
    ('JavaScript: linguagem da web', 'Conceitos essenciais de JavaScript para interfaces e APIs.', 'PUBLIC', 'MANUAL'),
    ('TypeScript: tipos no frontend', 'Uso de tipos estaticos para reduzir erros em aplicacoes web.', 'PUBLIC', 'MANUAL'),
    ('C: memoria e baixo nivel', 'Fundamentos de linguagem C, memoria e compilacao.', 'PUBLIC', 'MANUAL'),
    ('C++: desempenho e abstracao', 'Conceitos de C++ moderno para software de alto desempenho.', 'PUBLIC', 'MANUAL'),
    ('C#: plataforma .NET', 'Fundamentos de C# e do ecossistema .NET.', 'PUBLIC', 'MANUAL'),
    ('Go: concorrencia e servicos', 'Conceitos de Go para servicos simples, concorrentes e performaticos.', 'PUBLIC', 'MANUAL'),
    ('Rust: seguranca de memoria', 'Principios de ownership, borrowing e seguranca sem garbage collector.', 'PUBLIC', 'MANUAL'),
    ('Kotlin: JVM moderna', 'Recursos de Kotlin para desenvolvimento conciso na JVM.', 'PUBLIC', 'MANUAL'),
    ('Spring Boot: APIs Java', 'Principios de construcao de APIs com Spring Boot.', 'PUBLIC', 'MANUAL'),
    ('Vue.js: interfaces reativas', 'Fundamentos de componentes, estado e composicao em Vue.', 'PUBLIC', 'MANUAL'),
    ('React: componentes e estado', 'Conceitos centrais de React para interfaces declarativas.', 'PUBLIC', 'MANUAL'),
    ('Angular: aplicacoes estruturadas', 'Fundamentos de Angular para formularios, componentes e servicos.', 'PUBLIC', 'MANUAL'),
    ('Node.js: runtime JavaScript', 'Uso de JavaScript no servidor com eventos e I/O assincrono.', 'PUBLIC', 'MANUAL'),
    ('Django: web com Python', 'Conceitos de Django para desenvolvimento web produtivo.', 'PUBLIC', 'MANUAL'),
    ('FastAPI: APIs Python', 'Construcao de APIs modernas com Python, tipos e documentacao automatica.', 'PUBLIC', 'MANUAL'),
    ('Laravel: web com PHP', 'Fundamentos de Laravel para rotas, modelos e organizacao web.', 'PUBLIC', 'MANUAL'),
    ('Machine Learning: fundamentos', 'Conceitos iniciais de aprendizado supervisionado, dados e avaliacao.', 'PUBLIC', 'MANUAL'),
    ('Aprendizado supervisionado', 'Classificacao, regressao, treino e avaliacao de modelos.', 'PUBLIC', 'MANUAL'),
    ('Aprendizado nao supervisionado', 'Agrupamento, reducao de dimensionalidade e exploracao de dados.', 'PUBLIC', 'MANUAL'),
    ('Deep Learning: redes neurais', 'Nocoes essenciais sobre camadas, ativacoes e treinamento profundo.', 'PUBLIC', 'MANUAL'),
    ('Redes neurais convolucionais', 'CNNs aplicadas a imagens, filtros e hierarquias de caracteristicas.', 'PUBLIC', 'MANUAL'),
    ('Transformers e atencao', 'Arquiteturas baseadas em atencao para linguagem e sequencias.', 'PUBLIC', 'MANUAL'),
    ('Neurociencia: neuronios e sinapses', 'Bases biologicas da comunicacao neural.', 'PUBLIC', 'MANUAL'),
    ('Neurociencia cognitiva', 'Relacao entre cerebro, comportamento, memoria e atencao.', 'PUBLIC', 'MANUAL'),
    ('Psicologia cognitiva', 'Processos mentais como memoria, percepcao, linguagem e decisao.', 'PUBLIC', 'MANUAL'),
    ('Psicologia da aprendizagem', 'Condicionamento, reforco, transferencia e pratica deliberada.', 'PUBLIC', 'MANUAL'),
    ('Memoria humana', 'Modelos de memoria, esquecimento e recuperacao.', 'PUBLIC', 'MANUAL'),
    ('Metodos de pesquisa em comportamento', 'Desenhos experimentais, validade e analise em ciencias comportamentais.', 'PUBLIC', 'MANUAL');

INSERT INTO cards (deck_id, front_html, back_html, source_note_id)
VALUES
    ((SELECT id FROM decks WHERE title = 'Java: fundamentos modernos' ORDER BY id DESC LIMIT 1), 'O que caracteriza Java como linguagem multiplataforma?', 'O codigo Java compila para bytecode executado pela JVM, permitindo rodar em diferentes sistemas com a maquina virtual adequada.', 'seed-public-001-a'),
    ((SELECT id FROM decks WHERE title = 'Java: fundamentos modernos' ORDER BY id DESC LIMIT 1), 'Por que usar tipos fortes em Java?', 'Tipos fortes ajudam o compilador a detectar inconsistencias antes da execucao.', 'seed-public-001-b'),
    ((SELECT id FROM decks WHERE title = 'Python: fundamentos para ciencia de dados' ORDER BY id DESC LIMIT 1), 'Por que Python e comum em ciencia de dados?', 'A linguagem combina sintaxe simples com bibliotecas maduras para analise, visualizacao e aprendizado de maquina.', 'seed-public-002-a'),
    ((SELECT id FROM decks WHERE title = 'Python: fundamentos para ciencia de dados' ORDER BY id DESC LIMIT 1), 'Qual papel de listas e dicionarios em Python?', 'Listas organizam sequencias de valores; dicionarios associam chaves a valores.', 'seed-public-002-b'),
    ((SELECT id FROM decks WHERE title = 'JavaScript: linguagem da web' ORDER BY id DESC LIMIT 1), 'Onde JavaScript normalmente executa?', 'No navegador e tambem no servidor, por exemplo com Node.js.', 'seed-public-003-a'),
    ((SELECT id FROM decks WHERE title = 'JavaScript: linguagem da web' ORDER BY id DESC LIMIT 1), 'O que e uma Promise?', 'E um objeto que representa a conclusao futura de uma operacao assincrona.', 'seed-public-003-b'),
    ((SELECT id FROM decks WHERE title = 'TypeScript: tipos no frontend' ORDER BY id DESC LIMIT 1), 'O que TypeScript adiciona ao JavaScript?', 'Um sistema de tipos estaticos e ferramentas de verificacao antes da execucao.', 'seed-public-004-a'),
    ((SELECT id FROM decks WHERE title = 'TypeScript: tipos no frontend' ORDER BY id DESC LIMIT 1), 'Por que interfaces sao uteis em TypeScript?', 'Elas descrevem contratos de objetos e ajudam a documentar estruturas esperadas.', 'seed-public-004-b'),
    ((SELECT id FROM decks WHERE title = 'C: memoria e baixo nivel' ORDER BY id DESC LIMIT 1), 'O que e um ponteiro em C?', 'E uma variavel que armazena o endereco de memoria de outro valor.', 'seed-public-005-a'),
    ((SELECT id FROM decks WHERE title = 'C: memoria e baixo nivel' ORDER BY id DESC LIMIT 1), 'Por que C exige cuidado com memoria?', 'Porque o programador gerencia alocacao, acesso e liberacao com menor protecao automatica.', 'seed-public-005-b'),
    ((SELECT id FROM decks WHERE title = 'C++: desempenho e abstracao' ORDER BY id DESC LIMIT 1), 'O que C++ combina em seu desenho?', 'Recursos de baixo nivel com abstracoes como classes, templates e RAII.', 'seed-public-006-a'),
    ((SELECT id FROM decks WHERE title = 'C++: desempenho e abstracao' ORDER BY id DESC LIMIT 1), 'O que RAII busca garantir?', 'Que recursos sejam adquiridos e liberados junto ao ciclo de vida dos objetos.', 'seed-public-006-b'),
    ((SELECT id FROM decks WHERE title = 'C#: plataforma .NET' ORDER BY id DESC LIMIT 1), 'Qual ecossistema executa C# principalmente?', 'A plataforma .NET.', 'seed-public-007-a'),
    ((SELECT id FROM decks WHERE title = 'C#: plataforma .NET' ORDER BY id DESC LIMIT 1), 'O que LINQ facilita em C#?', 'Consultas e transformacoes sobre colecoes com sintaxe integrada.', 'seed-public-007-b'),
    ((SELECT id FROM decks WHERE title = 'Go: concorrencia e servicos' ORDER BY id DESC LIMIT 1), 'O que sao goroutines?', 'Unidades leves de execucao concorrente gerenciadas pelo runtime de Go.', 'seed-public-008-a'),
    ((SELECT id FROM decks WHERE title = 'Go: concorrencia e servicos' ORDER BY id DESC LIMIT 1), 'Para que servem channels em Go?', 'Para comunicacao e sincronizacao entre goroutines.', 'seed-public-008-b'),
    ((SELECT id FROM decks WHERE title = 'Rust: seguranca de memoria' ORDER BY id DESC LIMIT 1), 'O que ownership controla em Rust?', 'Quem e responsavel por um valor e quando ele deve ser liberado.', 'seed-public-009-a'),
    ((SELECT id FROM decks WHERE title = 'Rust: seguranca de memoria' ORDER BY id DESC LIMIT 1), 'Por que borrowing e importante?', 'Permite usar referencias sem transferir propriedade, obedecendo regras de seguranca.', 'seed-public-009-b'),
    ((SELECT id FROM decks WHERE title = 'Kotlin: JVM moderna' ORDER BY id DESC LIMIT 1), 'Qual vantagem Kotlin oferece na JVM?', 'Sintaxe concisa com interoperabilidade com bibliotecas Java.', 'seed-public-010-a'),
    ((SELECT id FROM decks WHERE title = 'Kotlin: JVM moderna' ORDER BY id DESC LIMIT 1), 'Como Kotlin trata nulidade?', 'Com tipos nullable explicitos, reduzindo erros de referencia nula.', 'seed-public-010-b'),
    ((SELECT id FROM decks WHERE title = 'Spring Boot: APIs Java' ORDER BY id DESC LIMIT 1), 'O que Spring Boot simplifica?', 'Configuracao e criacao de aplicacoes Spring prontas para execucao.', 'seed-public-011-a'),
    ((SELECT id FROM decks WHERE title = 'Spring Boot: APIs Java' ORDER BY id DESC LIMIT 1), 'Qual papel de controllers em uma API?', 'Receber requisicoes HTTP e direcionar a logica adequada.', 'seed-public-011-b'),
    ((SELECT id FROM decks WHERE title = 'Vue.js: interfaces reativas' ORDER BY id DESC LIMIT 1), 'O que e reatividade em Vue?', 'Atualizacao automatica da interface quando o estado muda.', 'seed-public-012-a'),
    ((SELECT id FROM decks WHERE title = 'Vue.js: interfaces reativas' ORDER BY id DESC LIMIT 1), 'Para que servem componentes?', 'Para dividir a interface em partes reutilizaveis e organizadas.', 'seed-public-012-b'),
    ((SELECT id FROM decks WHERE title = 'React: componentes e estado' ORDER BY id DESC LIMIT 1), 'Qual ideia central de React?', 'Construir interfaces a partir de componentes declarativos.', 'seed-public-013-a'),
    ((SELECT id FROM decks WHERE title = 'React: componentes e estado' ORDER BY id DESC LIMIT 1), 'O que estado representa em React?', 'Dados que podem mudar e provocar nova renderizacao do componente.', 'seed-public-013-b'),
    ((SELECT id FROM decks WHERE title = 'Angular: aplicacoes estruturadas' ORDER BY id DESC LIMIT 1), 'Qual caracteristica marca Angular?', 'Um framework completo com componentes, injecao de dependencias, rotas e formularios.', 'seed-public-014-a'),
    ((SELECT id FROM decks WHERE title = 'Angular: aplicacoes estruturadas' ORDER BY id DESC LIMIT 1), 'Para que servem services em Angular?', 'Para concentrar logica compartilhada e acesso a dados.', 'seed-public-014-b'),
    ((SELECT id FROM decks WHERE title = 'Node.js: runtime JavaScript' ORDER BY id DESC LIMIT 1), 'O que Node.js permite?', 'Executar JavaScript fora do navegador, especialmente em servidores e ferramentas.', 'seed-public-015-a'),
    ((SELECT id FROM decks WHERE title = 'Node.js: runtime JavaScript' ORDER BY id DESC LIMIT 1), 'Por que o modelo de eventos e importante?', 'Ele favorece I/O assincrono e alta concorrencia em operacoes de rede.', 'seed-public-015-b'),
    ((SELECT id FROM decks WHERE title = 'Django: web com Python' ORDER BY id DESC LIMIT 1), 'Qual filosofia Django costuma seguir?', 'Baterias inclusas: oferecer recursos comuns de aplicacoes web no proprio framework.', 'seed-public-016-a'),
    ((SELECT id FROM decks WHERE title = 'Django: web com Python' ORDER BY id DESC LIMIT 1), 'O que o ORM do Django abstrai?', 'Mapeamento entre objetos Python e tabelas do banco de dados.', 'seed-public-016-b'),
    ((SELECT id FROM decks WHERE title = 'FastAPI: APIs Python' ORDER BY id DESC LIMIT 1), 'O que FastAPI usa para validacao?', 'Anotacoes de tipo e modelos de dados para validar entradas e gerar documentacao.', 'seed-public-017-a'),
    ((SELECT id FROM decks WHERE title = 'FastAPI: APIs Python' ORDER BY id DESC LIMIT 1), 'Qual beneficio da documentacao automatica?', 'Facilita testar e entender endpoints sem escrever documentacao manual inicial.', 'seed-public-017-b'),
    ((SELECT id FROM decks WHERE title = 'Laravel: web com PHP' ORDER BY id DESC LIMIT 1), 'O que Laravel fornece para web?', 'Rotas, ORM, templates, migrations e ferramentas para produtividade.', 'seed-public-018-a'),
    ((SELECT id FROM decks WHERE title = 'Laravel: web com PHP' ORDER BY id DESC LIMIT 1), 'Qual papel do Eloquent?', 'E o ORM do Laravel para trabalhar com modelos e banco de dados.', 'seed-public-018-b'),
    ((SELECT id FROM decks WHERE title = 'Machine Learning: fundamentos' ORDER BY id DESC LIMIT 1), 'O que e um modelo em Machine Learning?', 'Uma funcao ajustada a dados para fazer previsoes ou reconhecer padroes.', 'seed-public-019-a'),
    ((SELECT id FROM decks WHERE title = 'Machine Learning: fundamentos' ORDER BY id DESC LIMIT 1), 'Por que separar treino e teste?', 'Para estimar desempenho em dados nao vistos e reduzir avaliacao enganosa.', 'seed-public-019-b'),
    ((SELECT id FROM decks WHERE title = 'Aprendizado supervisionado' ORDER BY id DESC LIMIT 1), 'O que caracteriza aprendizado supervisionado?', 'Uso de exemplos com rotulos ou respostas conhecidas durante o treinamento.', 'seed-public-020-a'),
    ((SELECT id FROM decks WHERE title = 'Aprendizado supervisionado' ORDER BY id DESC LIMIT 1), 'Qual diferenca entre classificacao e regressao?', 'Classificacao prediz categorias; regressao prediz valores numericos.', 'seed-public-020-b'),
    ((SELECT id FROM decks WHERE title = 'Aprendizado nao supervisionado' ORDER BY id DESC LIMIT 1), 'O que falta no aprendizado nao supervisionado?', 'Rotulos explicitos para guiar o treinamento.', 'seed-public-021-a'),
    ((SELECT id FROM decks WHERE title = 'Aprendizado nao supervisionado' ORDER BY id DESC LIMIT 1), 'Para que serve agrupamento?', 'Para encontrar grupos de exemplos semelhantes nos dados.', 'seed-public-021-b'),
    ((SELECT id FROM decks WHERE title = 'Deep Learning: redes neurais' ORDER BY id DESC LIMIT 1), 'O que caracteriza deep learning?', 'Modelos com muitas camadas capazes de aprender representacoes complexas.', 'seed-public-022-a'),
    ((SELECT id FROM decks WHERE title = 'Deep Learning: redes neurais' ORDER BY id DESC LIMIT 1), 'O que e uma funcao de ativacao?', 'Uma funcao que introduz nao linearidade entre camadas da rede.', 'seed-public-022-b'),
    ((SELECT id FROM decks WHERE title = 'Redes neurais convolucionais' ORDER BY id DESC LIMIT 1), 'Por que convolucoes sao uteis em imagens?', 'Elas detectam padroes locais como bordas, texturas e formas.', 'seed-public-023-a'),
    ((SELECT id FROM decks WHERE title = 'Redes neurais convolucionais' ORDER BY id DESC LIMIT 1), 'O que pooling costuma fazer?', 'Reduz dimensoes e resume informacoes locais.', 'seed-public-023-b'),
    ((SELECT id FROM decks WHERE title = 'Transformers e atencao' ORDER BY id DESC LIMIT 1), 'Qual mecanismo central dos transformers?', 'Atencao, especialmente self-attention.', 'seed-public-024-a'),
    ((SELECT id FROM decks WHERE title = 'Transformers e atencao' ORDER BY id DESC LIMIT 1), 'O que self-attention permite?', 'Relacionar partes de uma sequencia entre si para construir representacoes contextualizadas.', 'seed-public-024-b'),
    ((SELECT id FROM decks WHERE title = 'Neurociencia: neuronios e sinapses' ORDER BY id DESC LIMIT 1), 'O que e uma sinapse?', 'Uma conexao funcional pela qual neuronios transmitem sinais.', 'seed-public-025-a'),
    ((SELECT id FROM decks WHERE title = 'Neurociencia: neuronios e sinapses' ORDER BY id DESC LIMIT 1), 'Qual papel dos neurotransmissores?', 'Mediar comunicacao quimica entre celulas nervosas.', 'seed-public-025-b'),
    ((SELECT id FROM decks WHERE title = 'Neurociencia cognitiva' ORDER BY id DESC LIMIT 1), 'O que a neurociencia cognitiva investiga?', 'Relacoes entre processos mentais e sistemas cerebrais.', 'seed-public-026-a'),
    ((SELECT id FROM decks WHERE title = 'Neurociencia cognitiva' ORDER BY id DESC LIMIT 1), 'Por que memoria e atencao sao estudadas juntas?', 'Porque a selecao de informacao influencia codificacao, recuperacao e desempenho.', 'seed-public-026-b'),
    ((SELECT id FROM decks WHERE title = 'Psicologia cognitiva' ORDER BY id DESC LIMIT 1), 'Qual foco da psicologia cognitiva?', 'Processos mentais como percepcao, memoria, linguagem e tomada de decisao.', 'seed-public-027-a'),
    ((SELECT id FROM decks WHERE title = 'Psicologia cognitiva' ORDER BY id DESC LIMIT 1), 'O que e carga cognitiva?', 'A demanda mental imposta por uma tarefa ao sistema de processamento.', 'seed-public-027-b'),
    ((SELECT id FROM decks WHERE title = 'Psicologia da aprendizagem' ORDER BY id DESC LIMIT 1), 'O que e reforco na aprendizagem?', 'Consequencia que aumenta a probabilidade de um comportamento se repetir.', 'seed-public-028-a'),
    ((SELECT id FROM decks WHERE title = 'Psicologia da aprendizagem' ORDER BY id DESC LIMIT 1), 'Por que feedback importa?', 'Ele orienta correcao de erro e ajuste de estrategia.', 'seed-public-028-b'),
    ((SELECT id FROM decks WHERE title = 'Memoria humana' ORDER BY id DESC LIMIT 1), 'O que e recuperacao ativa?', 'Tentar lembrar uma informacao antes de consultar a resposta.', 'seed-public-029-a'),
    ((SELECT id FROM decks WHERE title = 'Memoria humana' ORDER BY id DESC LIMIT 1), 'O que a curva do esquecimento descreve?', 'A tendencia de perda de informacao ao longo do tempo sem revisao.', 'seed-public-029-b'),
    ((SELECT id FROM decks WHERE title = 'Metodos de pesquisa em comportamento' ORDER BY id DESC LIMIT 1), 'O que e validade interna?', 'Grau em que um estudo sustenta relacao causal sem confundidores relevantes.', 'seed-public-030-a'),
    ((SELECT id FROM decks WHERE title = 'Metodos de pesquisa em comportamento' ORDER BY id DESC LIMIT 1), 'Por que operacionalizar variaveis?', 'Para transformar conceitos abstratos em medidas observaveis ou manipulaveis.', 'seed-public-030-b');
